name = "505th Auxilary Mod"
author = "505th Aux Team"
prefix = "OLI"
mainprefix = "BLU"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0
[lints.config.file_type]
options.allow_no_extension = true

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_505aux.png",
    "logo_505aux_ca.paa",
    "LICENSE.md",
    "README.md",
]
exclude = ["*.spp", "*.spp.painter_lock", "*.psd"]

[properties]
author = "505th Aux Team"
url = "https://github.com/DreadDrakeIII/505-Aux-Mod"

[hemtt.launch.default]
workshop = [
    "450814997",  # CBA_A3
    "463939057", # ACE
    "3499977893", # ADT
    "623475643",  # 3DEN
    "1779063631", # ZEN
    "2291129343", # Improved Melee System
    "767380317", # Blastcore # Only used to test particle effects
    "769440155", # Operation TREBUCHET
    "3325103983", # Combat Equipment Evolved
    "1572627279", # OPTRE First Contact
    "570118882", # No Weapon Sway
    "3328314886", # Heavy Weapon Framework
    "3038821437", # UNSC Foundries
    "3038826897", # UNSC Foundries Ace Compat
    "3300894429", # WBK Kit Menu
    "3165450999", # WBK Immersive Animations
    "2933180786", # WebKnight's OPTRE Expansion
    "2915485125", # Burn 'Em Redux
    "3391132245", # Advanced Vault System: SPARTANS Expansion
    "2794721649", # Advanced Vault System: Remastered
    "3255508422", # HALO Flamethrower
    "2888477598", # 1st MEU Aux Mod
    # "2522638637", # ACE Arsenal Extended
    "366425329", # FIR AWS(AirWeaponSystem)
    "784218341", # The Mighty GAU-8 Avenger
    "949698441", # The Mighty GAU-8 Avenger - ACE
    "2987115897", # Weapon Research and Security: Firearms
    "3469976535", # Weapon Research and Security: Autonomous systems
    "3423561449", # Equipment PLUS
    "3283642267", # Speshal Core
    "3283645995", # Breach - Rewrite
    "3283652320", # Melee - Rewrite
    "1960024802", # PLP All in One
    "1923321700", # O&T Expansion Eden
    "3489262669", # Expanded Actions and Vehicle Animations
    "2958273599", # Modular Warehouse Parts
    "2975882889", # Modular Shoothouse Parts
    "366423278", # F-16 Fighting Falcon
]
presets = ["main"]
dlc = []
optionals = []
mission = "AuxTest.VR"
parameters = []

[hemtt.launch.previews]
extends = "default"
mission = "Previews.VR"
parameters = ["-name=Previews"]